[package]
name = "noir_zkemail"
type = "bin"
authors = ["Mach 34"]
compiler_version = ">=0.32.0"

[dependencies]
noir_rsa = { tag = "v0.2", git = "https://github.com/noir-lang/noir_rsa" }
string_search = { tag = "v0.1", git = "https://github.com/noir-lang/noir_string_search"  }
