[package]
name = "verify_email_2048_bit_dkim"
type = "bin"
authors = ["Mach 34"]
compiler_version = ">=1.0.0"

[dependencies]
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" }
zkemail = { path =  "../../lib"}